'use client';
import {Check,Minus,Plus,X} from 'lucide-react';
import {forwardRef,useState} from 'react';

export function Button({variant='primary',className='',...p}:React.ButtonHTMLAttributes<HTMLButtonElement>&{variant?:'primary'|'secondary'|'ghost'|'danger'|'outline'}){
  const styles={primary:'bg-green text-[#07130b] hover:bg-green/90',secondary:'bg-elevated hover:bg-line',ghost:'bg-transparent hover:bg-white/5',danger:'bg-danger text-white',outline:'border border-line hover:border-green'}[variant];
  return <button className={`focus-ring min-h-12 rounded-xl px-5 py-3 font-bold transition disabled:opacity-50 ${styles} ${className}`} {...p}/>;
}
export function Card({children,className=''}:{children:React.ReactNode,className?:string}){return <section className={`glass rounded-2xl p-5 ${className}`}>{children}</section>}
export const Input=forwardRef<HTMLInputElement,React.InputHTMLAttributes<HTMLInputElement>&{label:string,error?:string;helper?:string}>(({label,error,helper,...p},ref)=><label className="grid gap-2 text-sm font-semibold">{label}<input ref={ref} className={`focus-ring min-h-12 rounded-xl border bg-surface px-4 text-base ${error?'border-danger':'border-line'}`} {...p}/>{error&&<span className="text-xs text-danger">{error}</span>}{helper&&<span className="text-xs text-slate-400">{helper}</span>}</label>);Input.displayName='Input';
export function Select({label,children,...p}:React.SelectHTMLAttributes<HTMLSelectElement>&{label:string}){return <label className="grid gap-2 text-sm font-semibold">{label}<select className="min-h-12 rounded-xl border border-line bg-surface px-4" {...p}>{children}</select></label>}
export function Badge({children,variant='neutral'}:{children:React.ReactNode,variant?:'success'|'warning'|'danger'|'info'|'neutral'}){const c={success:'bg-green/15 text-green',warning:'bg-amber/15 text-amber',danger:'bg-danger/15 text-red-300',info:'bg-info/15 text-blue-300',neutral:'bg-white/10 text-slate-300'}[variant];return <span className={`inline-flex rounded-full px-3 py-1 text-xs font-bold ${c}`}>{children}</span>}
export function ProgressBar({value}:{value:number}){return <div className="h-2 overflow-hidden rounded-full bg-line"><div className="h-full rounded-full bg-green transition-all" style={{width:`${Math.max(0,Math.min(100,value))}%`}}/></div>}
export function Skeleton({className='h-24'}:{className?:string}){return <div className={`animate-pulse rounded-2xl bg-elevated ${className}`}/>}
export function EmptyState({title,description}:{title:string,description:string}){return <Card className="text-center"><p className="font-heading text-lg font-bold">{title}</p><p className="mt-2 text-sm text-slate-400">{description}</p></Card>}
export function Modal({open,onClose,children}:{open:boolean,onClose:()=>void,children:React.ReactNode}){if(!open)return null;return <div className="fixed inset-0 z-50 grid items-end bg-black/70 sm:place-items-center" onClick={onClose}><div className="w-full max-w-lg rounded-t-3xl border border-line bg-card p-5 sm:rounded-3xl" onClick={e=>e.stopPropagation()}><button onClick={onClose} className="float-right p-2" aria-label="Tutup"><X/></button>{children}</div></div>}
export function RPESelector({value,onChange}:{value:number,onChange:(n:number)=>void}){return <div><div className="mb-2 flex justify-between text-sm"><span>RPE sesi</span><b className={value>=9?'text-danger':value>=8?'text-amber':'text-green'}>{value}/10</b></div><input className="w-full accent-green" type="range" min="1" max="10" value={value} onChange={e=>onChange(Number(e.target.value))}/></div>}
export function WeightInput({value,onChange}:{value:number,onChange:(n:number)=>void}){return <label className="grid gap-2 text-sm font-semibold">Berat badan<div className="flex rounded-xl border border-line bg-surface"><input className="min-h-12 flex-1 bg-transparent px-4" type="number" step=".1" value={value||''} onChange={e=>onChange(Number(e.target.value))}/><span className="grid place-items-center px-4 text-slate-400">kg</span></div></label>}
export function SetLogger({set,value,onChange}:{set:number,value:{weightKg:number,reps:number,completed:boolean},onChange:(v:any)=>void}){return <div className={`grid grid-cols-[auto_1fr_1fr_auto] items-end gap-2 rounded-xl border p-3 ${value.completed?'border-green/50 bg-green/5':'border-line'}`}><b className="pb-3">{set}</b><label className="text-xs text-slate-400">kg<input className="mt-1 w-full rounded-lg bg-surface p-2 text-base" type="number" value={value.weightKg||''} onChange={e=>onChange({...value,weightKg:Number(e.target.value)})}/></label><label className="text-xs text-slate-400">reps<input className="mt-1 w-full rounded-lg bg-surface p-2 text-base" type="number" value={value.reps||''} onChange={e=>onChange({...value,reps:Number(e.target.value)})}/></label><button onClick={()=>onChange({...value,completed:!value.completed})} aria-label="Set selesai" className={`mb-1 grid size-10 place-items-center rounded-full ${value.completed?'bg-green text-black':'bg-elevated'}`}>{value.completed?<Check/>:<Plus/>}</button></div>}
